spring:
  application:
    name: service-provider
server:
  port: 8088
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://192.168.31.39:8761/eureka/, http://192.168.39.128:8761/eureka/'
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    # 以下均是默认值
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90