spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: 'http://192.168.31.39:8761/eureka/, http://192.168.39.128:8761/eureka/'
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
# 去除自我保护机制（方便测试服务异常）
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 600000
management:
  server:
    port: 8888